version: '3.8'
services:
  app:
    image: bookstorebe:0.0.1-SNAPSHOT
    container_name: bookstore
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/bookstore
