CREATE TABLE orders
(
    orderid INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId INT NOT NULL ,
    PRIMARY KEY(orderid)
);

CREATE TABLE bookorders
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orderid INT NOT NULL,
    bookid INT NOT NULL,
    CONSTRAINT foreignkey_orders
        FOREIGN KEY(orderid)
        REFERENCES orders(orderid)
);